import 'package:quiz_biblico_5/utils/app_routes.dart';

class RoutesBooks {
  /// Routes Books
  Map<String, String> routes = {
    // Routes Book Genesis
    'Gênesis': AppRoutes.bookGenesis,
    'GênesisQuestions': AppRoutes.questionsBookGenesis,
    'GênesisAnswerA': AppRoutes.alternative1BookGenesis,
    'GênesisAnswerB': AppRoutes.alternative2BookGenesis,
    'GênesisAnswerC': AppRoutes.alternative3BookGenesis,
    // Routes Book Exodus
    'Êxodo': AppRoutes.bookExodus,
    'ÊxodoQuestions': AppRoutes.questionsBookExodus,
    'ÊxodoAnswerA': AppRoutes.alternative1BookExodus,
    'ÊxodoAnswerB': AppRoutes.alternative2BookExodus,
    'ÊxodoAnswerC': AppRoutes.alternative3BookExodus,
    // Routes Book Leviticus
    'Levítico': AppRoutes.bookLeviticus,
    'LevíticoQuestions': AppRoutes.questionsBookLeviticus,
    'LevíticoAnswerA': AppRoutes.alternative1BookLeviticus,
    'LevíticoAnswerB': AppRoutes.alternative2BookLeviticus,
    'LevíticoAnswerC': AppRoutes.alternative3BookLeviticus,
    // Routes Book Numbers
    'Números': AppRoutes.bookNumbers,
    'NúmerosQuestions': AppRoutes.questionsBookNumbers,
    'NúmerosAnswerA': AppRoutes.alternative1BookNumbers,
    'NúmerosAnswerB': AppRoutes.alternative2BookNumbers,
    'NúmerosAnswerC': AppRoutes.alternative3BookNumbers,
    // Routes Book Deuteronomy
    'Deuteronômio': AppRoutes.bookDeuteronomy,
    'DeuteronômioQuestions': AppRoutes.questionsBookDeuteronomy,
    'DeuteronômioAnswerA': AppRoutes.alternative1BookDeuteronomy,
    'DeuteronômioAnswerB': AppRoutes.alternative2BookDeuteronomy,
    'DeuteronômioAnswerC': AppRoutes.alternative3BookDeuteronomy,
    // Routes Book Josue
    'Josué': AppRoutes.bookJosue,
    'JosuéQuestions': AppRoutes.questionsBookJosue,
    'JosuéAnswerA': AppRoutes.alternative1BookJosue,
    'JosuéAnswerB': AppRoutes.alternative2BookJosue,
    'JosuéAnswerC': AppRoutes.alternative3BookJosue,
    // Routes Book Judges
    'Juízes': AppRoutes.bookJudges,
    'JuízesQuestions': AppRoutes.questionsBookJudges,
    'JuízesAnswerA': AppRoutes.alternative1BookJudges,
    'JuízesAnswerB': AppRoutes.alternative2BookJudges,
    'JuízesAnswerC': AppRoutes.alternative3BookJudges,
    // Routes Book Ruth
    'Rute': AppRoutes.bookRuth,
    'RuteQuestions': AppRoutes.questionsBookRuth,
    'RuteAnswerA': AppRoutes.alternative1BookRuth,
    'RuteAnswerB': AppRoutes.alternative2BookRuth,
    'RuteAnswerC': AppRoutes.alternative3BookRuth,
    // Routes Book 1Samuel
    '1Samuel': AppRoutes.book1Samuel,
    '1SamuelQuestions': AppRoutes.questionsBook1Samuel,
    '1SamuelAnswerA': AppRoutes.alternative1Book1Samuel,
    '1SamuelAnswerB': AppRoutes.alternative2Book1Samuel,
    '1SamuelAnswerC': AppRoutes.alternative3Book1Samuel,
    // Routes Book 2 Samuel
    '2Samuel': AppRoutes.book2Samuel,
    '2SamuelQuestions': AppRoutes.questionsBook2Samuel,
    '2SamuelAnswerA': AppRoutes.alternative1Book2Samuel,
    '2SamuelAnswerB': AppRoutes.alternative2Book2Samuel,
    '2SamuelAnswerC': AppRoutes.alternative3Book2Samuel,
    // Routes Book 1 Kings
    '1Reis': AppRoutes.book1Kings,
    '1ReisQuestions': AppRoutes.questionsBook1Kings,
    '1ReisAnswerA': AppRoutes.alternative1Book1Kings,
    '1ReisAnswerB': AppRoutes.alternative2Book1Kings,
    '1ReisAnswerC': AppRoutes.alternative3Book1Kings,
    // Routes Book 2 Kings
    '2Reis': AppRoutes.book2Kings,
    '2ReisQuestions': AppRoutes.questionsBook2Kings,
    '2ReisAnswerA': AppRoutes.alternative1Book2Kings,
    '2ReisAnswerB': AppRoutes.alternative2Book2Kings,
    '2ReisAnswerC': AppRoutes.alternative3Book2Kings,
    // Routes Book 1 Chronicles
    '1Crônicas': AppRoutes.book1Chronicles,
    '1CrônicasQuestions': AppRoutes.questionsBook1Chronicles,
    '1CrônicasAnswerA': AppRoutes.alternative1Book1Chronicles,
    '1CrônicasAnswerB': AppRoutes.alternative2Book1Chronicles,
    '1CrônicasAnswerC': AppRoutes.alternative3Book1Chronicles,
    // Routes Book 2 Chronicles
    '2Crônicas': AppRoutes.book2Chronicles,
    '2CrônicasQuestions': AppRoutes.questionsBook2Chronicles,
    '2CrônicasAnswerA': AppRoutes.alternative1Book2Chronicles,
    '2CrônicasAnswerB': AppRoutes.alternative2Book2Chronicles,
    '2CrônicasAnswerC': AppRoutes.alternative3Book2Chronicles,
    // Routes Book Ezra
    'Esdras': AppRoutes.bookEzra,
    'EsdrasQuestions': AppRoutes.questionsBookEzra,
    'EsdrasAnswerA': AppRoutes.alternative1BookEzra,
    'EsdrasAnswerB': AppRoutes.alternative2BookEzra,
    'EsdrasAnswerC': AppRoutes.alternative3BookEzra,
    // Routes Book Nehemiah
    'Neemias': AppRoutes.bookNehemiah,
    'NeemiasQuestions': AppRoutes.questionsBookNehemiah,
    'NeemiasAnswerA': AppRoutes.alternative1BookNehemiah,
    'NeemiasAnswerB': AppRoutes.alternative2BookNehemiah,
    'NeemiasAnswerC': AppRoutes.alternative3BookNehemiah,
    // Routes Book Ester
    'Ester': AppRoutes.bookEster,
    'EsterQuestions': AppRoutes.questionsBookEster,
    'EsterAnswerA': AppRoutes.alternative1BookEster,
    'EsterAnswerB': AppRoutes.alternative2BookEster,
    'EsterAnswerC': AppRoutes.alternative3BookEster,
    // Routes Book Job
    'Jó': AppRoutes.bookJob,
    'JóQuestions': AppRoutes.questionsBookJob,
    'JóAnswerA': AppRoutes.alternative1BookJob,
    'JóAnswerB': AppRoutes.alternative2BookJob,
    'JóAnswerC': AppRoutes.alternative3BookJob,
    // Routes Book Psalms
    'Salmos': AppRoutes.bookPsalms,
    'SalmosQuestions': AppRoutes.questionsBookPsalms,
    'SalmosAnswerA': AppRoutes.alternative1BookPsalms,
    'SalmosAnswerB': AppRoutes.alternative2BookPsalms,
    'SalmosAnswerC': AppRoutes.alternative3BookPsalms,
    // Routes Book Proverbs
    'Provérbios': AppRoutes.bookProverbs,
    'ProvérbiosQuestions': AppRoutes.questionsBookProverbs,
    'ProvérbiosAnswerA': AppRoutes.alternative1BookProverbs,
    'ProvérbiosAnswerB': AppRoutes.alternative2BookProverbs,
    'ProvérbiosAnswerC': AppRoutes.alternative3BookProverbs,
    // Routes Book Ecclesiastes
    'Eclesiastes': AppRoutes.bookEcclesiastes,
    'EclesiastesQuestions': AppRoutes.questionsBookEcclesiastes,
    'EclesiastesAnswerA': AppRoutes.alternative1BookEcclesiastes,
    'EclesiastesAnswerB': AppRoutes.alternative2BookEcclesiastes,
    'EclesiastesAnswerC': AppRoutes.alternative3BookEcclesiastes,
    // Routes Book Songs
    'Cântares': AppRoutes.bookSongs,
    'CântaresQuestions': AppRoutes.questionsBookSongs,
    'CântaresAnswerA': AppRoutes.alternative1BookSongs,
    'CântaresAnswerB': AppRoutes.alternative2BookSongs,
    'CântaresAnswerC': AppRoutes.alternative3BookSongs,
    // Routes Book Isaiah
    'Isaías': AppRoutes.bookIsaiah,
    'IsaíasQuestions': AppRoutes.questionsBookIsaiah,
    'IsaíasAnswerA': AppRoutes.alternative1BookIsaiah,
    'IsaíasAnswerB': AppRoutes.alternative2BookIsaiah,
    'IsaíasAnswerC': AppRoutes.alternative3BookIsaiah,
    // Routes Book Jeremiah
    'Jeremias': AppRoutes.bookJeremiah,
    'JeremiasQuestions': AppRoutes.questionsBookJeremiah,
    'JeremiasAnswerA': AppRoutes.alternative1BookJeremiah,
    'JeremiasAnswerB': AppRoutes.alternative2BookJeremiah,
    'JeremiasAnswerC': AppRoutes.alternative3BookJeremiah,
    // Routes Book Lamentations
    'Lamentações': AppRoutes.bookLamentations,
    'LamentaçõesQuestions': AppRoutes.questionsBookLamentations,
    'LamentaçõesAnswerA': AppRoutes.alternative1BookLamentations,
    'LamentaçõesAnswerB': AppRoutes.alternative2BookLamentations,
    'LamentaçõesAnswerC': AppRoutes.alternative3BookLamentations,
    // Routes Book Ezequiel
    'Ezequiel': AppRoutes.bookEzequiel,
    'EzequielQuestions': AppRoutes.questionsBookEzequiel,
    'EzequielAnswerA': AppRoutes.alternative1BookEzequiel,
    'EzequielAnswerB': AppRoutes.alternative2BookEzequiel,
    'EzequielAnswerC': AppRoutes.alternative3BookEzequiel,
    // Routes Book Daniel
    'Daniel': AppRoutes.bookDaniel,
    'DanielQuestions': AppRoutes.questionsBookDaniel,
    'DanielAnswerA': AppRoutes.alternative1BookDaniel,
    'DanielAnswerB': AppRoutes.alternative2BookDaniel,
    'DanielAnswerC': AppRoutes.alternative3BookDaniel,
    // Routes Book Hosea
    'Oséias': AppRoutes.bookHosea,
    'OséiasQuestions': AppRoutes.questionsBookHosea,
    'OséiasAnswerA': AppRoutes.alternative1BookHosea,
    'OséiasAnswerB': AppRoutes.alternative2BookHosea,
    'OséiasAnswerC': AppRoutes.alternative3BookHosea,
    // Routes Book Joel
    'Joel': AppRoutes.bookJoel,
    'JoelQuestions': AppRoutes.questionsBookJoel,
    'JoelAnswerA': AppRoutes.alternative1BookJoel,
    'JoelAnswerB': AppRoutes.alternative2BookJoel,
    'JoelAnswerC': AppRoutes.alternative3BookJoel,
    // Routes Book Amos
    'Amós': AppRoutes.bookAmos,
    'AmósQuestions': AppRoutes.questionsBookAmos,
    'AmósAnswerA': AppRoutes.alternative1BookAmos,
    'AmósAnswerB': AppRoutes.alternative2BookAmos,
    'AmósAnswerC': AppRoutes.alternative3BookAmos,
    // Routes Book Obadiah
    'Obadias': AppRoutes.bookObadiah,
    'ObadiasQuestions': AppRoutes.questionsBookObadiah,
    'ObadiasAnswerA': AppRoutes.alternative1BookObadiah,
    'ObadiasAnswerB': AppRoutes.alternative2BookObadiah,
    'ObadiasAnswerC': AppRoutes.alternative3BookObadiah,
    // Routes Book Jonah
    'Jonas': AppRoutes.bookJonah,
    'JonasQuestions': AppRoutes.questionsBookJonah,
    'JonasAnswerA': AppRoutes.alternative1BookJonah,
    'JonasAnswerB': AppRoutes.alternative2BookJonah,
    'JonasAnswerC': AppRoutes.alternative3BookJonah,
    // Routes Book Micah
    'Miquéias': AppRoutes.bookMicah,
    'MiquéiasQuestions': AppRoutes.questionsBookMicah,
    'MiquéiasAnswerA': AppRoutes.alternative1BookMicah,
    'MiquéiasAnswerB': AppRoutes.alternative2BookMicah,
    'MiquéiasAnswerC': AppRoutes.alternative3BookMicah,
    // Routes Book No
    'Naum': AppRoutes.bookNo,
    'NaumQuestions': AppRoutes.questionsBookNo,
    'NaumAnswerA': AppRoutes.alternative1BookNo,
    'NaumAnswerB': AppRoutes.alternative2BookNo,
    'NaumAnswerC': AppRoutes.alternative3BookNo,
    // Routes Book Habakkuk
    'Habacuque': AppRoutes.bookHabakkuk,
    'HabacuqueQuestions': AppRoutes.questionsBookHabakkuk,
    'HabacuqueAnswerA': AppRoutes.alternative1BookHabakkuk,
    'HabacuqueAnswerB': AppRoutes.alternative2BookHabakkuk,
    'HabacuqueAnswerC': AppRoutes.alternative3BookHabakkuk,
    // Routes Book Zephanies
    'Sofonias': AppRoutes.bookZephanies,
    'SofoniasQuestions': AppRoutes.questionsBookZephanies,
    'SofoniasAnswerA': AppRoutes.alternative1BookZephanies,
    'SofoniasAnswerB': AppRoutes.alternative2BookZephanies,
    'SofoniasAnswerC': AppRoutes.alternative3BookZephanies,
    // Routes Book Haggai
    'Ageu': AppRoutes.bookHaggai,
    'AgeuQuestions': AppRoutes.questionsBookHaggai,
    'AgeuAnswerA': AppRoutes.alternative1BookHaggai,
    'AgeuAnswerB': AppRoutes.alternative2BookHaggai,
    'AgeuAnswerC': AppRoutes.alternative3BookHaggai,
    // Routes Book Zechariah
    'Zacarias': AppRoutes.bookZechariah,
    'ZacariasQuestions': AppRoutes.questionsBookZechariah,
    'ZacariasAnswerA': AppRoutes.alternative1BookZechariah,
    'ZacariasAnswerB': AppRoutes.alternative2BookZechariah,
    'ZacariasAnswerC': AppRoutes.alternative3BookZechariah,
    // Routes Book Malachi
    'Malaquias': AppRoutes.bookMalachi,
    'MalaquiasQuestions': AppRoutes.questionsBookMalachi,
    'MalaquiasAnswerA': AppRoutes.alternative1BookMalachi,
    'MalaquiasAnswerB': AppRoutes.alternative2BookMalachi,
    'MalaquiasAnswerC': AppRoutes.alternative3BookMalachi,
    // Routes Book Mateus
    'Mateus': AppRoutes.bookMateus,
    'MateusQuestions': AppRoutes.questionsBookMateus,
    'MateusAnswerA': AppRoutes.alternative1BookMateus,
    'MateusAnswerB': AppRoutes.alternative2BookMateus,
    'MateusAnswerC': AppRoutes.alternative3BookMateus,
    // Routes Book Frames
    'Marcos': AppRoutes.bookFrames,
    'MarcosQuestions': AppRoutes.questionsBookFrames,
    'MarcosAnswerA': AppRoutes.alternative1BookFrames,
    'MarcosAnswerB': AppRoutes.alternative2BookFrames,
    'MarcosAnswerC': AppRoutes.alternative3BookFrames,
    // Routes Book Lucas
    'Lucas': AppRoutes.bookLucas,
    'LucasQuestions': AppRoutes.questionsBookLucas,
    'LucasAnswerA': AppRoutes.alternative1BookLucas,
    'LucasAnswerB': AppRoutes.alternative2BookLucas,
    'LucasAnswerC': AppRoutes.alternative3BookLucas,
    // Routes Book John
    'Evangelho de João': AppRoutes.bookJohn,
    'Evangelho de JoãoQuestions': AppRoutes.questionsBookJohn,
    'Evangelho de JoãoAnswerA': AppRoutes.alternative1BookJohn,
    'Evangelho de JoãoAnswerB': AppRoutes.alternative2BookJohn,
    'Evangelho de JoãoAnswerC': AppRoutes.alternative3BookJohn,
    // Routes Book Acts
    'Atos': AppRoutes.bookActs,
    'AtosQuestions': AppRoutes.questionsBookActs,
    'AtosAnswerA': AppRoutes.alternative1BookActs,
    'AtosAnswerB': AppRoutes.alternative2BookActs,
    'AtosAnswerC': AppRoutes.alternative3BookActs,
    // Routes Book Romans
    'Romanos': AppRoutes.bookRomans,
    'RomanosQuestions': AppRoutes.questionsBookRomans,
    'RomanosAnswerA': AppRoutes.alternative1BookRomans,
    'RomanosAnswerB': AppRoutes.alternative2BookRomans,
    'RomanosAnswerC': AppRoutes.alternative3BookRomans,
    // Routes Book 1 Corinthians
    '1 Coríntios': AppRoutes.book1Corinthians,
    '1 CoríntiosQuestions': AppRoutes.questionsBook1Corinthians,
    '1 CoríntiosAnswerA': AppRoutes.alternative1Book1Corinthians,
    '1 CoríntiosAnswerB': AppRoutes.alternative2Book1Corinthians,
    '1 CoríntiosAnswerC': AppRoutes.alternative3Book1Corinthians,
    // Routes Book 2 Corinthians
    '2 Coríntios': AppRoutes.book2Corinthians,
    '2 CoríntiosQuestions': AppRoutes.questionsBook2Corinthians,
    '2 CoríntiosAnswerA': AppRoutes.alternative1Book2Corinthians,
    '2 CoríntiosAnswerB': AppRoutes.alternative2Book2Corinthians,
    '2 CoríntiosAnswerC': AppRoutes.alternative3Book2Corinthians,
    // Routes Book Galatians
    'Gálatas': AppRoutes.bookGalatians,
    'GálatasQuestions': AppRoutes.questionsBookGalatians,
    'GálatasAnswerA': AppRoutes.alternative1BookGalatians,
    'GálatasAnswerB': AppRoutes.alternative2BookGalatians,
    'GálatasAnswerC': AppRoutes.alternative3BookGalatians,
    // Routes Book Ephesians
    'Efésios': AppRoutes.bookEphesians,
    'EfésiosQuestions': AppRoutes.questionsBookEphesians,
    'EfésiosAnswerA': AppRoutes.alternative1BookEphesians,
    'EfésiosAnswerB': AppRoutes.alternative2BookEphesians,
    'EfésiosAnswerC': AppRoutes.alternative3BookEphesians,
    // Routes Book Philippians
    'Filipenses': AppRoutes.bookPhilippians,
    'FilipensesQuestions': AppRoutes.questionsBookPhilippians,
    'FilipensesAnswerA': AppRoutes.alternative1BookPhilippians,
    'FilipensesAnswerB': AppRoutes.alternative2BookPhilippians,
    'FilipensesAnswerC': AppRoutes.alternative3BookPhilippians,
    // Routes Book Colossians
    'Colossenses': AppRoutes.bookColossians,
    'ColossensesQuestions': AppRoutes.questionsBookColossians,
    'ColossensesAnswerA': AppRoutes.alternative1BookColossians,
    'ColossensesAnswerB': AppRoutes.alternative2BookColossians,
    'ColossensesAnswerC': AppRoutes.alternative3BookColossians,
    // Routes Book 1 Thessalonians
    '1Tessalonicenses': AppRoutes.book1Thessalonians,
    '1TessalonicensesQuestions': AppRoutes.questionsBook1Thessalonians,
    '1TessalonicensesAnswerA': AppRoutes.alternative1Book1Thessalonians,
    '1TessalonicensesAnswerB': AppRoutes.alternative2Book1Thessalonians,
    '1TessalonicensesAnswerC': AppRoutes.alternative3Book1Thessalonians,
    // Routes Book 2 Thessalonians
    '2Tessalonicenses': AppRoutes.book2Thessalonians,
    '2TessalonicensesQuestions': AppRoutes.questionsBook2Thessalonians,
    '2TessalonicensesAnswerA': AppRoutes.alternative1Book2Thessalonians,
    '2TessalonicensesAnswerB': AppRoutes.alternative2Book2Thessalonians,
    '2TessalonicensesAnswerC': AppRoutes.alternative3Book2Thessalonians,
    // Routes Book 1 Timothy
    '1 Timóteo': AppRoutes.book1Timothy,
    '1 TimóteoQuestions': AppRoutes.questionsBook1Timothy,
    '1 TimóteoAnswerA': AppRoutes.alternative1Book1Timothy,
    '1 TimóteoAnswerB': AppRoutes.alternative2Book1Timothy,
    '1 TimóteoAnswerC': AppRoutes.alternative3Book1Timothy,
    // Routes Book 2 Timothy
    '2 Timóteo': AppRoutes.book2Timothy,
    '2 TimóteoQuestions': AppRoutes.questionsBook2Timothy,
    '2 TimóteoAnswerA': AppRoutes.alternative1Book2Timothy,
    '2 TimóteoAnswerB': AppRoutes.alternative2Book2Timothy,
    '2 TimóteoAnswerC': AppRoutes.alternative3Book2Timothy,
    // Routes Book Tito
    'Tito': AppRoutes.bookTito,
    'TitoQuestions': AppRoutes.questionsBookTito,
    'TitoAnswerA': AppRoutes.alternative1BookTito,
    'TitoAnswerB': AppRoutes.alternative2BookTito,
    'TitoAnswerC': AppRoutes.alternative3BookTito,
    // Routes Book Philemon
    'Filemom': AppRoutes.bookPhilemon,
    'FilemomQuestions': AppRoutes.questionsBookPhilemon,
    'FilemomAnswerA': AppRoutes.alternative1BookPhilemon,
    'FilemomAnswerB': AppRoutes.alternative2BookPhilemon,
    'FilemomAnswerC': AppRoutes.alternative3BookPhilemon,
    // Routes Book Hebrews
    'Hebreus': AppRoutes.bookHebrews,
    'HebreusQuestions': AppRoutes.questionsBookHebrews,
    'HebreusAnswerA': AppRoutes.alternative1BookHebrews,
    'HebreusAnswerB': AppRoutes.alternative2BookHebrews,
    'HebreusAnswerC': AppRoutes.alternative3BookHebrews,
    // Routes Book Tiago
    'Tiago': AppRoutes.bookTiago,
    'TiagoQuestions': AppRoutes.questionsBookTiago,
    'TiagoAnswerA': AppRoutes.alternative1BookTiago,
    'TiagoAnswerB': AppRoutes.alternative2BookTiago,
    'TiagoAnswerC': AppRoutes.alternative3BookTiago,
    // Routes Book 1 Peter
    '1 Pedro': AppRoutes.book1Peter,
    '1 PedroQuestions': AppRoutes.questionsBook1Peter,
    '1 PedroAnswerA': AppRoutes.alternative1Book1Peter,
    '1 PedroAnswerB': AppRoutes.alternative2Book1Peter,
    '1 PedroAnswerC': AppRoutes.alternative3Book1Peter,
    // Routes Book 2 Peter
    '2 Pedro': AppRoutes.book2Peter,
    '2 PedroQuestions': AppRoutes.questionsBook2Peter,
    '2 PedroAnswerA': AppRoutes.alternative1Book2Peter,
    '2 PedroAnswerB': AppRoutes.alternative2Book2Peter,
    '2 PedroAnswerC': AppRoutes.alternative3Book2Peter,
    // Routes Book 1 John
    '1 João': AppRoutes.book1John,
    '1 JoãoQuestions': AppRoutes.questionsBook1John,
    '1 JoãoAnswerA': AppRoutes.alternative1Book1John,
    '1 JoãoAnswerB': AppRoutes.alternative2Book1John,
    '1 JoãoAnswerC': AppRoutes.alternative3Book1John,
    // Routes Book 2 John
    '2 João': AppRoutes.book2John,
    '2 JoãoQuestions': AppRoutes.questionsBook2John,
    '2 JoãoAnswerA': AppRoutes.alternative1Book2John,
    '2 JoãoAnswerB': AppRoutes.alternative2Book2John,
    '2 JoãoAnswerC': AppRoutes.alternative3Book2John,
    // Routes Book 3 John
    '3 João': AppRoutes.book3John,
    '3 JoãoQuestions': AppRoutes.questionsBook3John,
    '3 JoãoAnswerA': AppRoutes.alternative1Book3John,
    '3 JoãoAnswerB': AppRoutes.alternative2Book3John,
    '3 JoãoAnswerC': AppRoutes.alternative3Book3John,
    // Routes Book Judas
    'Judas': AppRoutes.bookJudas,
    'JudasQuestions': AppRoutes.questionsBookJudas,
    'JudasAnswerA': AppRoutes.alternative1BookJudas,
    'JudasAnswerB': AppRoutes.alternative2BookJudas,
    'JudasAnswerC': AppRoutes.alternative3BookJudas,
    // Routes Book Apocalypse
    'Apocalipse': AppRoutes.bookApocalypse,
    'ApocalipseQuestions': AppRoutes.questionsBookApocalypse,
    'ApocalipseAnswerA': AppRoutes.alternative1BookApocalypse,
    'ApocalipseAnswerB': AppRoutes.alternative2BookApocalypse,
    'ApocalipseAnswerC': AppRoutes.alternative3BookApocalypse,
  };
}
